### PR TITLE
#1: creating molecule environment

### PR DESCRIPTION
**Pull request by Karina5005**
- [X] initialize role with Molecule and Vagrant
- [X] configure prerequisites and make sure tests done succussefully
- [X] move developed tasks from test playbook to that role

### CODE REVIEW

**Comment by Karina5005** [comment]
Pull created by Mishavint at 2022-11-18T08:23:48Z

**Review by a-alex-l — COMMENTED** [review]
LGTM

**Comment by Karina5005** [comment]
This PR is included in version 1.0.0 :tada:
Comment created by github-actions[bot] at 2023-05-02T21:29:44Z

**Comment by Karina5005** [comment]
@bissquit, 
I have several questions

1) Should i implement some simple CI?
2) Should i enable branch protection for main branch? So It will require PR approval
Comment created by Mishavint at 2022-11-18T08:29:12Z

**Comment by Karina5005** [comment]
> bissquit, I have several questions
> 
> 1. Should i implement some simple CI?
> 2. Should i enable branch protection for main branch? So It will require PR approval

1. No
2. It's mostly for public repositories. So the answer is - not now
Comment created by bissquit at 2022-11-22T12:35:01Z

**Comment by Karina5005** [comment]
Assignee is {'login': 'Mishavint'}

**Pull request closed without merging**
